# Generated by Django 4.1.6 on 2023-04-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='money_to_pay',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
