# Generated by Django 4.1.6 on 2023-04-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_alter_borrowing_actual_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='actual_return',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
