# Generated by Django 4.1.6 on 2023-04-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0003_alter_borrowing_actual_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='actual_return',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='borrow_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='expected_return',
            field=models.DateField(),
        ),
    ]
